### ISSUE TITLE
create user

### ISSUE THREAD

**Issue by ChengXu2016** [sharemen/confulenceclient#2]
铁汁，这里面有create user相关内容吗？谢谢

**Comment by sharemen** [comment]
还没有，我研究研究的~

**Comment by sharemen** [comment]
查了一下confluence rest api并没有支持creat user相关操作
只有查询类功能 getUser  getMemberInfo 我顺手加了一下
具体rest api支持列表详见
https://docs.atlassian.com/ConfluenceServer/rest/7.11.0/
